### ISSUE TITLE
[error] org.fusesource.scalate.TemplateException:

### ISSUE THREAD

**Issue by geocarvalho** [dnanexus/dxCompiler#457]
Hi team, I'm trying to compile a WDL workflow and I have this error:
```bash
$ java -jar /path/to/apps/dxCompiler-2.11.4.jar compile wgs_qc_wf.wdl -project project-F292qGQ02k8Y48QfFzJqX2j0 -folder /apps/wdl_wf/wgs_qc_wf/ -f
[error] org.fusesource.scalate.TemplateException:
  bad constant pool index: 0 at pos: 48445
     while compiling: <no file>
        during phase: globalPhase=<no phase>, enteringPhase=<some phase>
     library version: version 2.13.7
    compiler version: version 2.13.7
  reconstructed args: -dependencyfile none -deprecation -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws -classpath /Users/gcarvalhoneto/Documents/apps/dxCompiler-2.11.4.jar -d /var/folders/ml/m0gn1_b5737fr2617kl9mzymkfh1ym/T/scalate-15682643873275838727-workdir/classes

  last tree to typer: EmptyTree
       tree position: <unknown>
            tree tpe: <notype>
              symbol: null
           call site: <none> in <none>

== Source file context for tree position ==


	at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:864)
	at org.fusesource.scalate.TemplateEngine.compileAndLoadEntry(TemplateEngine.scala:725)
	at org.fusesource.scalate.TemplateEngine.liftedTree1$1(TemplateEngine.scala:436)
	at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:430)
	at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:485)
	at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:582)
	at wdlTools.generators.Renderer.render(Renderer.scala:15)
	at dx.compiler.ApplicationCompiler.generateJobScript(ApplicationCompiler.scala:139)
	at dx.compiler.ApplicationCompiler.createRunSpec(ApplicationCompiler.scala:189)
	at dx.compiler.ApplicationCompiler.apply(ApplicationCompiler.scala:552)
	at dx.compiler.Compiler$BundleCompiler.maybeBuildApplet(Compiler.scala:357)
	at dx.compiler.Compiler$BundleCompiler.$anonfun$apply$1(Compiler.scala:471)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:926)
	at dx.compiler.Compiler$BundleCompiler.apply(Compiler.scala:441)
	at dx.compiler.Compiler.apply(Compiler.scala:494)
	at dxCompiler.Main$.compile(Main.scala:538)
	at dxCompiler.Main$.dispatchCommand(Main.scala:791)
	at dxCompiler.Main$.main(Main.scala:922)
	at dxCompiler.MainApp$.delayedEndpoint$dxCompiler$MainApp$1(Main.scala:927)
	at dxCompiler.MainApp$delayedInit$body.apply(Main.scala:926)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at dxCompiler.MainApp$.main(Main.scala:926)
	at dxCompiler.MainApp.main(Main.scala)
Caused by: scala.reflect.internal.FatalError:
  bad constant pool index: 0 at pos: 48445
     while compiling: <no file>
        during phase: globalPhase=<no phase>, enteringPhase=<some phase>
     library version: version 2.13.7
    compiler version: version 2.13.7
  reconstructed args: -dependencyfile none -deprecation -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws -classpath /Users/gcarvalhoneto/Documents/apps/dxCompiler-2.11.4.jar -d /var/folders/ml/m0gn1_b5737fr2617kl9mzymkfh1ym/T/scalate-15682643873275838727-workdir/classes

  last tree to typer: EmptyTree
       tree position: <unknown>
            tree tpe: <notype>
              symbol: null
           call site: <none> in <none>

== Source file context for tree position ==


	at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
	at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.errorBadIndex(ClassfileParser.scala:407)
	at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getExternalName(ClassfileParser.scala:262)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.readParamNames$1(ClassfileParser.scala:853)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:859)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$6(ClassfileParser.scala:936)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:936)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseMethod(ClassfileParser.scala:635)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:548)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$2(ClassfileParser.scala:174)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:159)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:142)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:342)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.$anonfun$complete$2(SymbolLoaders.scala:249)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:247)
	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1561)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1533)
	at scala.reflect.internal.Definitions.scala$reflect$internal$Definitions$$enterNewMethod(Definitions.scala:47)
	at scala.reflect.internal.Definitions$DefinitionsClass.String_$plus$lzycompute(Definitions.scala:1256)
	at scala.reflect.internal.Definitions$DefinitionsClass.String_$plus(Definitions.scala:1256)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreMethods$lzycompute(Definitions.scala:1577)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreMethods(Definitions.scala:1559)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1590)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1590)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1646)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1226)
	at org.fusesource.scalate.support.ScalaCompiler.compile(ScalaCompiler.scala:101)
	at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:787)
	... 33 more
```

I don't understand the error, it also happens when I try to compile the applet individually.
Do you have any recommendation?

**Comment by geocarvalho** [comment]
The problem was an update to java, as soon as I change back it to java 11 it worked.
Sorry!
